server:
  port: "8400"

mongo:
    host: "mongodb+srv://db-mongodb-nyc1-71962-6157d0c7.mongo.ondigitalocean.com"
    port: "27017"
    database: "tweety-db"
    username: "tweety-user"
    password: "h6Jtda97kW41p823"

spring:
    data:
        mongodb:
            port: ${mongo.port}
            host: ${mongo.host}
            database: ${mongo.database}
            username: ${mongo.username}
            password: ${mongo.password}
            authentication-database: ${mongo.database}
